// Code generated by MockGen. DO NOT EDIT.
// Source: textui.go

// Package mocktextui is a generated GoMock package.
package mocktextui

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTextUI is a mock of TextUI interface
type MockTextUI struct {
	ctrl     *gomock.Controller
	recorder *MockTextUIMockRecorder
}

// MockTextUIMockRecorder is the mock recorder for MockTextUI
type MockTextUIMockRecorder struct {
	mock *MockTextUI
}

// NewMockTextUI creates a new mock instance
func NewMockTextUI(ctrl *gomock.Controller) *MockTextUI {
	mock := &MockTextUI{ctrl: ctrl}
	mock.recorder = &MockTextUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTextUI) EXPECT() *MockTextUIMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockTextUI) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run
func (mr *MockTextUIMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTextUI)(nil).Run))
}
